menu:
  about: /about
  archives: /archives

excerpt: true
feed: /atom.xml
repo: https://icylogic.net

duoshuo: 

cdn:
  normalize: '//dn-staticfile.qbox.me'    
  carbon: ''
  duoshuo: '//static.duoshuo.com'
  jQuery: '//dn-staticfile.qbox.me'
  pjax: '//dn-staticfile.qbox.me'    
  
